language: cpp
compiler: 
    - g++

install:
    - if ["$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - cmake
    - cmake-data
    - bluez
    - libbluetooth-dev
    
script: 
  - ./travis-build.sh
  
notifications:
  emails:
    - tomoaki@tomy-tech.com
    
